//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALNWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EO_ALANSIS_SATIS
    {
        public int ID { get; set; }
        public string DURUM { get; set; }
        public string SIPARIS_TURU { get; set; }
        public string SINIF { get; set; }
        public string NAKLIYE { get; set; }
        public string PARTI { get; set; }
        public string MUSTERI { get; set; }
        public string ETD { get; set; }
        public string ETA { get; set; }
        public string KUTU { get; set; }
        public string AMBALAJ { get; set; }
        public string EBAT { get; set; }
        public string MIN_MEYVE_AGIRLIK { get; set; }
        public string MIN_KUTU_AGIRLIK { get; set; }
        public string PALET_ADET { get; set; }
        public string KUTU_ADET { get; set; }
        public string TONAJ_KG { get; set; }
        public string PLT_KUTU { get; set; }
        public string PALET_TIPI { get; set; }
        public string ACIKLAMA { get; set; }
        public string ETIKET { get; set; }
        public string MUSTERI_REFERANS { get; set; }
        public string TESLIM_SEKLI { get; set; }
        public string TESLIM_YERI { get; set; }
        public string RENK { get; set; }
        public string STOK_KODU { get; set; }
        public string STOK_ADI { get; set; }
        public string SATIS_ONAY { get; set; }
        public string LOJISTIK_ONAY { get; set; }
        public string URETIM_ONAY { get; set; }
        public string KALITE_ONAY { get; set; }
        public string MEYVE_ONAY { get; set; }
        public string ZIRAI_ONAY { get; set; }
        public string SON_ONAY { get; set; }
        public string GGN { get; set; }
        public string NOK_BIRIM { get; set; }
        public string URUN { get; set; }
        public string ISEMRI { get; set; }
        public string SEVK { get; set; }
    }
}
